title = "Custom rules"

[extend]
useDefault = true

[[rules]]
id = "internal-urls"
description = "Identify internal urls"
regex = '''${GITLEAKS_REGEX_INTERNAL_URL}'''
tags = ["internal-urls"]

[[rules]]
id = "banned-ids"
description = "Identify banned IDs"
regex = '''${GITLEAKS_REGEX_BANNED_IDS}'''
tags = ["banned-ids"]

[allowlist]
description = "Global allowlist"
paths = [
  ".idea/.*",
  "(.*/)?target/.*",
  ".gitreview"
]
regexes = [
  '''(?i).*query\.local-justice.*''',
  '''(?i).*referencedata\.query\.local-justice-areas.*''',
  '''(?i).*referencedata\.local-authority-address.*''',
  '''(?i).*referencedata\.local-justice-area-address.*''',
  '''(?i).*referencedata\.query\.local.*''',
  '''(?i).*vnd\.referencedata\.query\.local.*''',
  '''(?i).*referencedata\.local.*'''
]

